#!/bin/bash



CheckIfValidOfName() {
    input=$1

    if [ -f "$input" ]; then
        echo "The DB already exists"
        return 1 
    elif [[ $input =~ ^[a-zA-Z]+[0-9]*$ ]]; then
        input=$(echo "$input" | tr ' ' '_')
	return 0
    elif [ -z $input ];then
	echo "your input is empty"
	return 1
    else
        echo "Invalid input try again"
	return 1
        
    fi
}

CheckIfValid_OfNum() {
    input=$1
    if [[ $input =~  ^[0-9]+$ && "$num_col" -gt 0 ]]; then
        input=$(echo "$input" | tr ' ' '_')
	return 0
    elif [ -z $input ];then
	echo "your input is empty"
	return 1
    else
        echo "Invalid input try again"
	return 1
        
    fi
}
